# -*- coding: utf-8 -*-
"""it5437_2026_assignment_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PROJtr6b3Oo1-3_mRQgMGBu_RKGqWFd6
"""

# ============================================
# SETUP
# ============================================
import numpy as np
import cv2
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from scipy import ndimage
import os

# Path to your images
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/data1'

# Helper functions for display
def imshow(img, title="", cmap=None, figsize=(6,6)):
    plt.figure(figsize=figsize)
    if cmap == 'gray':
        plt.imshow(img, cmap='gray', vmin=0, vmax=255)
    elif len(img.shape) == 3:
        plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
    else:
        plt.imshow(img, cmap=cmap)
    plt.title(title)
    plt.axis('off')
    plt.show()

def plot_histogram(img, title="Histogram"):
    plt.figure(figsize=(8,4))
    if len(img.shape) == 3:
        colors = ('b','g','r')
        for i, color in enumerate(colors):
            hist = cv2.calcHist([img], [i], None, [256], [0,256])
            plt.plot(hist, color=color)
    else:
        plt.hist(img.ravel(), bins=256, color='gray', alpha=0.7)
    plt.title(title)
    plt.xlabel('Pixel Intensity')
    plt.ylabel('Frequency')
    plt.xlim([0,256])
    plt.show()

def plot_images_grid(images, titles, cols=2, figsize=(15,5)):
    rows = (len(images) + cols - 1) // cols
    plt.figure(figsize=figsize)
    for i, (img, title) in enumerate(zip(images, titles)):
        plt.subplot(rows, cols, i+1)
        if len(img.shape) == 3:
            plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        else:
            plt.imshow(img, cmap='gray')
        plt.title(title)
        plt.axis('off')
    plt.tight_layout()
    plt.show()

print("Setup complete!")

# ============================================
# QUESTION 1: Intensity Transforms
# ============================================

runway = cv2.imread(os.path.join(DATA_PATH, 'Figure 1 Runway.png'))
imshow(runway, "Original Runway Image")

def gamma_correction(img, gamma):
    img_norm = img.astype(np.float32) / 255.0
    corrected = np.power(img_norm, gamma)
    return (corrected * 255).astype(np.uint8)

def contrast_stretching(img, r1=0.2, r2=0.8):
    img_norm = img.astype(np.float32) / 255.0
    s = np.zeros_like(img_norm)

    mask1 = img_norm <= r1
    mask2 = (img_norm > r1) & (img_norm <= r2)
    mask3 = img_norm > r2

    s[mask1] = 0
    s[mask2] = (img_norm[mask2] - r1) / (r2 - r1)
    s[mask3] = 1.0

    return (s * 255).astype(np.uint8)

gamma_05 = gamma_correction(runway, 0.5)
gamma_2 = gamma_correction(runway, 2.0)
contrast_stretched = contrast_stretching(runway)

plot_images_grid([runway, gamma_05, gamma_2, contrast_stretched],
                 ['Original', 'Gamma=0.5', 'Gamma=2.0', 'Contrast Stretched'],
                 cols=2, figsize=(12,10))

fig, axes = plt.subplots(2, 2, figsize=(12, 8))
titles = ['Original', 'Gamma=0.5', 'Gamma=2.0', 'Contrast Stretched']
images = [runway, gamma_05, gamma_2, contrast_stretched]

for ax, img, title in zip(axes.flat, images, titles):
    if len(img.shape) == 3:
        colors = ('b','g','r')
        for i, color in enumerate(colors):
            hist = cv2.calcHist([img], [i], None, [256], [0,256])
            ax.plot(hist, color=color)
    ax.set_title(title)
    ax.set_xlim([0,256])
plt.tight_layout()
plt.show()

# ============================================
# QUESTION 2: Gamma Correction in L*a*b* Space
# ============================================

img_q2 = cv2.imread(os.path.join(DATA_PATH, 'Figure 2 Image for gamma correction.jpg'))
imshow(img_q2, "Original Image for Q2")

def gamma_correct_L_channel(img, gamma):
    lab = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    L, a, b = cv2.split(lab)

    L_norm = L.astype(np.float32) / 100.0
    L_corrected = np.power(L_norm, gamma) * 100.0
    L_corrected = L_corrected.astype(np.uint8)

    lab_corrected = cv2.merge([L_corrected, a, b])
    return cv2.cvtColor(lab_corrected, cv2.COLOR_LAB2BGR)

gamma_value = 0.6
img_corrected = gamma_correct_L_channel(img_q2, gamma_value)

print(f"Applied gamma correction with γ = {gamma_value}")

plot_images_grid([img_q2, img_corrected],
                 ['Original', f'L-channel Gamma Corrected (γ={gamma_value})'],
                 figsize=(12,5))

fig, axes = plt.subplots(1, 2, figsize=(12, 4))
for ax, img, title in zip(axes, [img_q2, img_corrected],
                          ['Original Histogram', 'Corrected Histogram']):
    colors = ('b','g','r')
    for i, color in enumerate(colors):
        hist = cv2.calcHist([img], [i], None, [256], [0,256])
        ax.plot(hist, color=color)
    ax.set_title(title)
    ax.set_xlim([0,256])
plt.tight_layout()
plt.show()

# ============================================
# QUESTION 3: Custom Histogram Equalization
# ============================================

def my_histogram_equalization(img):
    if len(img.shape) == 3:
        yuv = cv2.cvtColor(img, cv2.COLOR_BGR2YUV)
        y_channel = yuv[:,:,0]
        equalized_y = equalize_single_channel(y_channel)
        yuv[:,:,0] = equalized_y
        return cv2.cvtColor(yuv, cv2.COLOR_YUV2BGR)
    else:
        return equalize_single_channel(img)

def equalize_single_channel(img):
    hist, bins = np.histogram(img.flatten(), 256, [0,256])
    cdf = hist.cumsum()
    cdf_m = np.ma.masked_equal(cdf, 0)
    cdf_m = (cdf_m - cdf_m.min()) * 255 / (cdf_m.max() - cdf_m.min())
    cdf = np.ma.filled(cdf_m, 0).astype('uint8')
    img_equalized = cdf[img]
    return img_equalized

runway = cv2.imread(os.path.join(DATA_PATH, 'Figure 1 Runway.png'))
runway_equalized = my_histogram_equalization(runway)

runway_opencv_eq = cv2.cvtColor(runway, cv2.COLOR_BGR2YUV)
runway_opencv_eq[:,:,0] = cv2.equalizeHist(runway_opencv_eq[:,:,0])
runway_opencv_eq = cv2.cvtColor(runway_opencv_eq, cv2.COLOR_YUV2BGR)

plot_images_grid([runway, runway_equalized, runway_opencv_eq],
                 ['Original', 'Custom Equalization', 'OpenCV Equalization'],
                 cols=3, figsize=(15,5))

fig, axes = plt.subplots(1, 3, figsize=(15, 4))
images = [runway, runway_equalized, runway_opencv_eq]
titles = ['Original', 'Custom Equalized', 'OpenCV Equalized']

for ax, img, title in zip(axes, images, titles):
    colors = ('b','g','r')
    for i, color in enumerate(colors):
        hist = cv2.calcHist([img], [i], None, [256], [0,256])
        ax.plot(hist, color=color)
    ax.set_title(title)
    ax.set_xlim([0,256])
plt.tight_layout()
plt.show()

# ============================================
# QUESTION 4: Otsu and Foreground Equalization
# ============================================

woman = cv2.imread(os.path.join(DATA_PATH, 'Figure 3 Woman standing in front of an open door.jpg'))
gray_woman = cv2.cvtColor(woman, cv2.COLOR_BGR2GRAY)

thresh_val, binary_mask = cv2.threshold(gray_woman, 0, 255,
                                         cv2.THRESH_BINARY + cv2.THRESH_OTSU)
print(f"Otsu threshold value: {thresh_val}")

foreground_pixels = gray_woman[binary_mask == 255]
result_woman = gray_woman.copy()

if len(foreground_pixels) > 0:
    hist_fg, bins = np.histogram(foreground_pixels, 256, [0,256])
    cdf_fg = hist_fg.cumsum()
    cdf_m = np.ma.masked_equal(cdf_fg, 0)
    cdf_m = (cdf_m - cdf_m.min()) * 255 / (cdf_m.max() - cdf_m.min())
    cdf_fg = np.ma.filled(cdf_m, 0).astype('uint8')

    fg_indices = np.where(binary_mask == 255)
    result_woman[fg_indices] = cdf_fg[gray_woman[fg_indices]]

plot_images_grid([gray_woman, binary_mask, result_woman],
                 ['Grayscale Original', 'Otsu Binary Mask', 'Foreground Equalized'],
                 cols=3, figsize=(15,5))

# ============================================
# QUESTION 5: Gaussian Filtering
# ============================================

def create_gaussian_kernel(size, sigma):
    kernel = np.zeros((size, size))
    center = size // 2

    for i in range(size):
        for j in range(size):
            x = i - center
            y = j - center
            kernel[i, j] = (1 / (2 * np.pi * sigma**2)) * \
                          np.exp(-(x**2 + y**2) / (2 * sigma**2))

    return kernel / kernel.sum()

kernel_5x5 = create_gaussian_kernel(5, 2)
print("5x5 Gaussian Kernel (sigma=2):")
print(np.round(kernel_5x5, 4))

kernel_51x51 = create_gaussian_kernel(51, 2)

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')
x = np.arange(51)
y = np.arange(51)
X, Y = np.meshgrid(x, y)
surf = ax.plot_surface(X, Y, kernel_51x51, cmap='viridis')
ax.set_title('51x51 Gaussian Kernel (σ=2)')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Coefficient')
fig.colorbar(surf)
plt.show()

runway_gray = cv2.cvtColor(runway, cv2.COLOR_BGR2GRAY)
manual_gaussian = cv2.filter2D(runway_gray, -1, kernel_5x5)
opencv_gaussian = cv2.GaussianBlur(runway_gray, (5,5), 2)

plot_images_grid([runway_gray, manual_gaussian, opencv_gaussian],
                 ['Original Grayscale', 'Manual Gaussian', 'OpenCV GaussianBlur'],
                 cols=3, figsize=(15,5))

diff = np.abs(manual_gaussian.astype(np.float32) - opencv_gaussian.astype(np.float32))
print(f"Max difference: {diff.max():.4f}")
print(f"Mean difference: {diff.mean():.6f}")

# ============================================
# QUESTION 6: Derivative of Gaussian
# ============================================

def create_dog_kernel(size, sigma, direction='x'):
    kernel = np.zeros((size, size))
    center = size // 2

    for i in range(size):
        for j in range(size):
            x = i - center
            y = j - center
            g = (1 / (2 * np.pi * sigma**2)) * np.exp(-(x**2 + y**2) / (2 * sigma**2))

            if direction == 'x':
                kernel[i, j] = -x / (sigma**2) * g
            else:
                kernel[i, j] = -y / (sigma**2) * g

    return kernel

dog_x_5x5 = create_dog_kernel(5, 2, 'x')
dog_y_5x5 = create_dog_kernel(5, 2, 'y')

print("5x5 DoG Kernel (X-direction, sigma=2):")
print(np.round(dog_x_5x5, 4))

dog_x_51x51 = create_dog_kernel(51, 2, 'x')

fig = plt.figure(figsize=(12, 8))
ax = fig.add_subplot(111, projection='3d')
x = np.arange(51)
y = np.arange(51)
X, Y = np.meshgrid(x, y)
surf = ax.plot_surface(X, Y, dog_x_51x51, cmap='coolwarm')
ax.set_title('51x51 Derivative of Gaussian - X direction (σ=2)')
ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Coefficient')
fig.colorbar(surf)
plt.show()

grad_x_manual = cv2.filter2D(runway_gray.astype(np.float32), cv2.CV_32F, dog_x_5x5)
grad_y_manual = cv2.filter2D(runway_gray.astype(np.float32), cv2.CV_32F, dog_y_5x5)
grad_magnitude_manual = np.sqrt(grad_x_manual**2 + grad_y_manual**2)

grad_x_sobel = cv2.Sobel(runway_gray, cv2.CV_32F, 1, 0, ksize=3)
grad_y_sobel = cv2.Sobel(runway_gray, cv2.CV_32F, 0, 1, ksize=3)
grad_magnitude_sobel = np.sqrt(grad_x_sobel**2 + grad_y_sobel**2)

plot_images_grid([runway_gray,
                  cv2.normalize(grad_magnitude_manual, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8),
                  cv2.normalize(grad_magnitude_sobel, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)],
                 ['Original', 'DoG Gradient Magnitude', 'Sobel Gradient Magnitude'],
                 cols=3, figsize=(15,5))

# ============================================
# QUESTION 7: Image Zooming with Interpolation
# ============================================

def nearest_neighbor_interpolation(img, scale_factor):
    h, w = img.shape[:2]
    new_h, new_w = int(h * scale_factor), int(w * scale_factor)

    if len(img.shape) == 3:
        zoomed = np.zeros((new_h, new_w, img.shape[2]), dtype=img.dtype)
        for c in range(img.shape[2]):
            for i in range(new_h):
                for j in range(new_w):
                    orig_i = min(int(i / scale_factor), h-1)
                    orig_j = min(int(j / scale_factor), w-1)
                    zoomed[i, j, c] = img[orig_i, orig_j, c]
    else:
        zoomed = np.zeros((new_h, new_w), dtype=img.dtype)
        for i in range(new_h):
            for j in range(new_w):
                orig_i = min(int(i / scale_factor), h-1)
                orig_j = min(int(j / scale_factor), w-1)
                zoomed[i, j] = img[orig_i, orig_j]

    return zoomed

def bilinear_interpolation(img, scale_factor):
    h, w = img.shape[:2]
    new_h, new_w = int(h * scale_factor), int(w * scale_factor)

    if len(img.shape) == 3:
        zoomed = np.zeros((new_h, new_w, img.shape[2]), dtype=np.float32)
        for c in range(img.shape[2]):
            for i in range(new_h):
                for j in range(new_w):
                    x = i / scale_factor
                    y = j / scale_factor

                    x1, y1 = int(np.floor(x)), int(np.floor(y))
                    x2, y2 = min(x1+1, h-1), min(y1+1, w-1)

                    wx = x - x1
                    wy = y - y1

                    zoomed[i, j, c] = (1-wx)*(1-wy)*img[x1, y1, c] + \
                                       wx*(1-wy)*img[x2, y1, c] + \
                                       (1-wx)*wy*img[x1, y2, c] + \
                                       wx*wy*img[x2, y2, c]
    else:
        zoomed = np.zeros((new_h, new_w), dtype=np.float32)
        for i in range(new_h):
            for j in range(new_w):
                x = i / scale_factor
                y = j / scale_factor

                x1, y1 = int(np.floor(x)), int(np.floor(y))
                x2, y2 = min(x1+1, h-1), min(y1+1, w-1)

                wx = x - x1
                wy = y - y1

                zoomed[i, j] = (1-wx)*(1-wy)*img[x1, y1] + \
                               wx*(1-wy)*img[x2, y1] + \
                               (1-wx)*wy*img[x1, y2] + \
                               wx*wy*img[x2, y2]

    return zoomed.astype(img.dtype)

def compute_nssd(img1, img2):
    # Ensure both images have the same dimensions
    if img1.shape != img2.shape:
        img2_resized = cv2.resize(img2, (img1.shape[1], img1.shape[0]))
    else:
        img2_resized = img2

    diff = img1.astype(np.float32) - img2_resized.astype(np.float32)
    ssd = np.sum(diff ** 2)
    return ssd / img1.size

# Load the images
im01_large = cv2.imread(os.path.join(DATA_PATH, 'im01.png'))
im01_small = cv2.imread(os.path.join(DATA_PATH, 'im01small.png'))

print(f"Large image dimensions: {im01_large.shape}")
print(f"Small image dimensions: {im01_small.shape}")

# Calculate scale factor to zoom small image to match large image
scale_h = im01_large.shape[0] / im01_small.shape[0]
scale_w = im01_large.shape[1] / im01_small.shape[1]
scale_factor = max(scale_h, scale_w)

print(f"Calculated scale factor: {scale_factor:.4f}")

# Apply interpolation methods
print("Applying Nearest Neighbor interpolation...")
nn_zoomed = nearest_neighbor_interpolation(im01_small, scale_factor)

print("Applying Bilinear interpolation...")
bilinear_zoomed = bilinear_interpolation(im01_small, scale_factor)

# Resize to exactly match large image dimensions
nn_zoomed_resized = cv2.resize(nn_zoomed, (im01_large.shape[1], im01_large.shape[0]))
bilinear_zoomed_resized = cv2.resize(bilinear_zoomed, (im01_large.shape[1], im01_large.shape[0]))

# Compute NSSD
nssd_nn = compute_nssd(im01_large, nn_zoomed_resized)
nssd_bilinear = compute_nssd(im01_large, bilinear_zoomed_resized)

print(f"\nResults:")
print(f"Normalized SSD - Nearest Neighbor: {nssd_nn:.4f}")
print(f"Normalized SSD - Bilinear: {nssd_bilinear:.4f}")

# Display results
plot_images_grid([im01_large, im01_small, nn_zoomed_resized, bilinear_zoomed_resized],
                 ['Original Large', 'Original Small',
                  f'Nearest Neighbor\n(NSSD={nssd_nn:.2f})',
                  f'Bilinear\n(NSSD={nssd_bilinear:.2f})'],
                 cols=2, figsize=(12,10))

# Show detailed comparison
h, w = im01_large.shape[:2]
plt.figure(figsize=(15,5))

# Select a region for detailed view (center region)
start_h, start_w = h//3, w//3
size_h, size_w = 100, 100

plt.subplot(141)
plt.imshow(cv2.cvtColor(im01_large[start_h:start_h+size_h, start_w:start_w+size_w], cv2.COLOR_BGR2RGB))
plt.title('Original Detail')
plt.axis('off')

plt.subplot(142)
plt.imshow(cv2.cvtColor(im01_small[start_h//4:start_h//4+size_h//4, start_w//4:start_w//4+size_w//4], cv2.COLOR_BGR2RGB))
plt.title('Small Image Detail')
plt.axis('off')

plt.subplot(143)
plt.imshow(cv2.cvtColor(nn_zoomed_resized[start_h:start_h+size_h, start_w:start_w+size_w], cv2.COLOR_BGR2RGB))
plt.title('Nearest Neighbor Detail')
plt.axis('off')

plt.subplot(144)
plt.imshow(cv2.cvtColor(bilinear_zoomed_resized[start_h:start_h+size_h, start_w:start_w+size_w], cv2.COLOR_BGR2RGB))
plt.title('Bilinear Detail')
plt.axis('off')

plt.tight_layout()
plt.show()

# Additional comparison with OpenCV's built-in methods
print("\n" + "="*50)
print("Comparison with OpenCV built-in methods")
print("="*50)

opencv_nn = cv2.resize(im01_small, (im01_large.shape[1], im01_large.shape[0]),
                       interpolation=cv2.INTER_NEAREST)
opencv_bilinear = cv2.resize(im01_small, (im01_large.shape[1], im01_large.shape[0]),
                             interpolation=cv2.INTER_LINEAR)

nssd_opencv_nn = compute_nssd(im01_large, opencv_nn)
nssd_opencv_bilinear = compute_nssd(im01_large, opencv_bilinear)

print(f"OpenCV Nearest Neighbor NSSD: {nssd_opencv_nn:.4f}")
print(f"OpenCV Bilinear NSSD: {nssd_opencv_bilinear:.4f}")
print(f"Difference (Manual NN - OpenCV NN): {abs(nssd_nn - nssd_opencv_nn):.6f}")
print(f"Difference (Manual Bilinear - OpenCV Bilinear): {abs(nssd_bilinear - nssd_opencv_bilinear):.6f}")

# ============================================
# QUESTION 8: Salt and Pepper Noise Removal
# ============================================

noisy_img = cv2.imread(os.path.join(DATA_PATH, 'Figure 4 Image corrupted with salt and pepper noise.png'))
noisy_gray = cv2.cvtColor(noisy_img, cv2.COLOR_BGR2GRAY)

gaussian_filtered = cv2.GaussianBlur(noisy_img, (5,5), 1.5)
median_filtered = cv2.medianBlur(noisy_img, 5)

plot_images_grid([noisy_img, gaussian_filtered, median_filtered],
                 ['Original (Salt & Pepper)', 'Gaussian Filtered', 'Median Filtered'],
                 cols=3, figsize=(15,5))

# ============================================
# QUESTION 9: Image Sharpening
# ============================================

emma = cv2.imread(os.path.join(DATA_PATH, 'daisy.jpg'))

img_to_sharpen = emma.copy()

gaussian_blur = cv2.GaussianBlur(img_to_sharpen, (5,5), 1.5)
unsharp_mask = cv2.addWeighted(img_to_sharpen, 1.5, gaussian_blur, -0.5, 0)

laplacian_kernel = np.array([[0, -1, 0],
                              [-1, 5, -1],
                              [0, -1, 0]])
laplacian_sharpened = cv2.filter2D(img_to_sharpen, -1, laplacian_kernel)

sharpen_kernel = np.array([[-1, -1, -1],
                            [-1, 9, -1],
                            [-1, -1, -1]])
custom_sharpened = cv2.filter2D(img_to_sharpen, -1, sharpen_kernel)

plot_images_grid([img_to_sharpen, unsharp_mask, laplacian_sharpened, custom_sharpened],
                 ['Original', 'Unsharp Mask', 'Laplacian', 'Custom Kernel'],
                 cols=2, figsize=(12,10))

# ============================================
# QUESTION 10: Bilateral Filtering
# ============================================

def manual_bilateral_filter(img, diameter, sigma_s, sigma_r):
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img.astype(np.float32)

    h, w = gray.shape
    result = np.zeros_like(gray, dtype=np.float32)
    radius = diameter // 2

    spatial_kernel = np.zeros((diameter, diameter), dtype=np.float32)
    for i in range(diameter):
        for j in range(diameter):
            dx = i - radius
            dy = j - radius
            spatial_kernel[i, j] = np.exp(-(dx**2 + dy**2) / (2 * sigma_s**2))

    padded = np.pad(gray, radius, mode='reflect')

    for i in range(h):
        for j in range(w):
            window = padded[i:i+diameter, j:j+diameter]
            center_val = gray[i, j]

            range_kernel = np.exp(-((window - center_val)**2) / (2 * sigma_r**2))
            combined = spatial_kernel * range_kernel
            combined = combined / (combined.sum() + 1e-10)

            result[i, j] = np.sum(window * combined)

    return result.astype(np.uint8)

img_bilateral = cv2.imread(os.path.join(DATA_PATH, 'einstein.png'))

diameter = 9
sigma_s = 75
sigma_r = 75

print("Processing bilateral filter...")
manual_bilateral = manual_bilateral_filter(img_bilateral, diameter, sigma_s, sigma_r)
gaussian_smooth = cv2.GaussianBlur(img_bilateral, (diameter, diameter), sigma_s/2)
opencv_bilateral = cv2.bilateralFilter(img_bilateral, diameter, sigma_r, sigma_s)

plot_images_grid([img_bilateral, gaussian_smooth, opencv_bilateral, manual_bilateral],
                 ['Original', 'Gaussian Blur', 'OpenCV Bilateral', 'Manual Bilateral'],
                 cols=2, figsize=(12,10))

# ============================================
# QUESTION 11: Spatial vs Frequency Domain
# ============================================

size = 51

box_filter = np.ones((5,5)) / 25
gaussian_filter = create_gaussian_kernel(5, 1)
laplacian_filter = np.array([[0, 1, 0],
                              [1, -4, 1],
                              [0, 1, 0]])

filters = [box_filter, gaussian_filter, laplacian_filter]
titles = ['Box Filter', 'Gaussian Filter', 'Laplacian Filter']

fig, axes = plt.subplots(2, 3, figsize=(15, 8))

for idx, (filt, title) in enumerate(zip(filters, titles)):
    padded = np.zeros((size, size))
    h, w = filt.shape
    padded[size//2-h//2:size//2+h//2+1, size//2-w//2:size//2+w//2+1] = filt

    fft = np.fft.fft2(padded)
    fft_shift = np.fft.fftshift(fft)
    magnitude = np.abs(fft_shift)

    axes[0, idx].imshow(filt, cmap='gray')
    axes[0, idx].set_title(f'{title} (Spatial)')

    axes[1, idx].imshow(np.log(magnitude + 1), cmap='hot')
    axes[1, idx].set_title(f'{title} (Frequency)')

plt.tight_layout()
plt.show()

# ============================================
# QUESTION 12: Homomorphic Filtering
# ============================================

def homomorphic_filter(img, cutoff=30, gamma_l=0.5, gamma_h=1.5, c=1):
    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    else:
        gray = img.copy()

    gray_float = gray.astype(np.float32)
    img_log = np.log1p(gray_float)

    f = np.fft.fft2(img_log)
    fshift = np.fft.fftshift(f)

    rows, cols = gray.shape
    crow, ccol = rows // 2, cols // 2

    u = np.arange(rows) - crow
    v = np.arange(cols) - ccol
    U, V = np.meshgrid(u, v, indexing='ij')
    D = np.sqrt(U**2 + V**2)

    H = (gamma_h - gamma_l) * (1 - np.exp(-c * (D**2) / (cutoff**2))) + gamma_l

    fshift_filtered = fshift * H
    f_ishift = np.fft.ifftshift(fshift_filtered)
    img_back = np.fft.ifft2(f_ishift)
    img_back = np.real(img_back)

    img_filtered = np.expm1(img_back)
    img_filtered = cv2.normalize(img_filtered, None, 0, 255, cv2.NORM_MINMAX)

    return img_filtered.astype(np.uint8), H

img_homomorphic = cv2.imread(os.path.join(DATA_PATH, 'Figure 3 Woman standing in front of an open door.jpg'))
gray_homo = cv2.cvtColor(img_homomorphic, cv2.COLOR_BGR2GRAY)

filtered_homo, filter_H = homomorphic_filter(img_homomorphic, cutoff=30, gamma_l=0.4, gamma_h=1.8, c=1)
equalized_homo = cv2.equalizeHist(gray_homo)

plot_images_grid([img_homomorphic, filtered_homo, equalized_homo],
                 ['Original', 'Homomorphic Filtered', 'Histogram Equalized'],
                 cols=3, figsize=(15,5))

plt.figure(figsize=(6,5))
plt.imshow(np.log(np.abs(np.fft.fftshift(filter_H)) + 1), cmap='hot', extent=[-1,1,-1,1])
plt.title('Homomorphic Filter Frequency Response')
plt.colorbar()
plt.show()